version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    command: ["./scripts/entrypoint.sh"]

  test:
    build:
      context: .
      dockerfile: Dockerfile.test
    command: ["./scripts/run_unit_tests.sh"]
