FROM python:3.11

ARG DEBIAN_FRONTEND=noninteractive

WORKDIR /app

COPY pyproject.toml poetry.lock ./

# Install dependencies only (cache the layer for faster builds)
RUN pip install poetry && \
    poetry config virtualenvs.create false && \
    poetry install --no-interaction --no-ansi --no-root

COPY server ./server
COPY scripts ./scripts
COPY python_boilerplate ./python_boilerplate
COPY tests ./tests
RUN chmod +x ./scripts/entrypoint.sh ./scripts/run_unit_tests.sh ./scripts/run_all_tests.sh ./scripts/run_mypy.sh

RUN poetry install --no-interaction --no-ansi

EXPOSE 8080

# By default run unit tests, can be overriden for other test types
CMD ["./scripts/run_all_tests.sh"]
